
IMAGE-UVP-FLEX=

DIAG_MODEL=uvp
DIAG_UI_MODEL=UniFiVOIP

UPYFCD_VER=
FCDIMG_VER=
UBNTLIB_VER=
TOOL_VER=

TOOLS-CONFIG= common/* common/.

TOOLS-UVP-FLEX+=$(TOOLS-CONFIG)
TOOLS-UVP-FLEX+= uvp/*

$(eval $(call ProductImage,UVP-FLEX,FCD-UVP-FLEX-$(VER)))
