#!/bin/sh
PREFIX="[back2art]: "
SLOT=0
TS=192.168.1.19
TTY="ttyUSB0"
PREMAC="fcecda000010"

COMMON_ARG="-s=0 -d=$TTY -ts=$TS -e=False -ed=False --no-upload"

do_echo(){
	echo $PREFIX $@
}

prepare_img(){
	sudo /usr/bin/python3 /usr/local/sbin/prepare_bsp_img.py --boardid="$1" --bomrev="$2"
	[ $? -eq 1 ] && echo "Download image Fail" && exit
}

b2a_qca9563(){
	prepare_img $1 $2
	sudo /usr/bin/python3 /usr/local/sbin/uap_qca9563_mfg.py -b="$1" $COMMON_ARG
}

b2a_ar9342(){
	prepare_img $1 $2
	sudo /usr/bin/python3 /usr/local/sbin/am_ar9342_mfg.py -b="$1" $COMMON_ARG
}

b2a_ar9342_old(){
	prepare_img $1 $2
	sudo /usr/bin/python3 /usr/local/sbin/am_ar9342_mfg_bsp.py -b="$1" $COMMON_ARG
}

b2a_acorn(){
	prepare_img $1 $2
	sudo /usr/bin/python3 /usr/local/sbin/af_ipq80xx_mfg.py -pline=AirFiber -b="$1" $COMMON_ARG
}

b2a_af_maple(){
	prepare_img $1 $2
	sudo /usr/bin/python3 /usr/local/sbin/af_ipq5018_mfg.py -pline=AirFiber -b="$1" $COMMON_ARG
}

b2a_dakota(){
	prepare_img $1 $2
	sudo /usr/bin/python3 /usr/local/sbin/af_ipq40xx_mfg.py -b="$1" $COMMON_ARG
}

b2a_u6_maple(){
	prepare_img $1 $2
	sudo /usr/bin/python3 /usr/local/sbin/u6_ipq5018_mfg.py -b="$1" -m=$PREMAC $COMMON_ARG
}

b2a_mt7628(){
	prepare_img $1 $2
	sudo /usr/bin/python3 /usr/local/sbin/afi_udw_mt7628_mfg.py -b="$1" $COMMON_ARG
}

sync_bspimages(){
	curl http://wingchun.corp.ubnt.com:8080/view/BSP/job/Image_Sync/build?token=bsp_images
	curl http://10.2.0.33:8080/view/BSP/job/Image_Sync/build?token=bsp_images
}

list_product(){
	do_echo "\nALL: Download all images\
		"
	sudo /usr/bin/python3 /usr/local/sbin/prepare_bsp_img.py --listpd=y

}

readme(){
	do_echo "ReadMe: Please connect your device to usb console and re-power on it after running the command."
	do_echo "Usage: back2art [sync/BOM/ALL]"
}



readme
if [ ! -e /dev/ttyUSB0 ];then
	do_echo "Error: Find no usb console"; exit;
fi

if [ $# -eq 0 ];then
	list_product
	do_echo "Error: Which Product need to back to art?"
else
	sync_bspimages
	case "$1" in
		sync)
			sync_bspimages
			do_echo "Please wait a miniute to sync the image"
			;;
		"ALL") prepare_img NA ALL;; # To download all bsp images
		113-00719) b2a_acorn ac11 $1;; #AF60-XR
		113-01206) b2a_acorn ac1a $1;; #wave-ap 113-01206 ac1a for 2.5G phy
		113-01005*) b2a_acorn ac15 $1;; #wave-mesh 113-01005
		113-01105) b2a_acorn ac16 $1;; #wave-ap-micro 113-01105
		113-01205) b2a_acorn ac19 $1;; #wave-pro 113-01205
		113-01070) b2a_af_maple a658 $1;; #wave-nano
		113-00738) b2a_dakota dc9e $1;; #AF60-LR
		113-01073) b2a_af_maple a659 $1;; #lbe-ax
		113-01029) b2a_mt7628 ea2e $1;; #udw-pro-pu
		113-01036) b2a_mt7628 ed15 $1;; #pdu-pro-hd
		113-01184) b2a_u6_maple a667 $1;; #UX
		113-01219) b2a_mt7628 ffff $1;; #USP-PDU-Power-Switch
		113-00497) b2a_ar9342 e7f9 $1;;
		113-00306-art) b2a_ar9342_old fffff $1;; #Wasp internel 2.4G NBM2-HP art image
		113-00306-ct) b2a_ar9342_old ffffe $1;; #Wasp internel 2.4G NBM2-HP ct image
		113-00391) b2a_qca9563 e517 $1;; #UAP-AC-Lite
		113-00390) b2a_qca9563 e537 $1;; #UAP-AC-Pro
		*) 
			list_product
			do_echo "Error: Not support $1"
			;;
	esac
fi


